//   Author:   Tadhg Coffey
//   Date  :   3/20/14
//   Homework assignment : 5
//   File: SelectPhoneWebMapActivity.java from Phone Web Map
//   Objective : User chooses via radio buttons to
//      dial a phone number, look up a web page
//      or search for a location on Google Maps
//****************************************************************

package com.phonewebmap.app;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioGroup;
import android.widget.Toast;


public class SelectPhoneWebMapActivity extends Activity
    implements RadioGroup.OnCheckedChangeListener,
    View.OnClickListener
{
    EditText userInput;
    RadioGroup radioGroup;
    Button goButton;

    String userInputString;
    String toastMessage;
    boolean checkedPhoneButton;
    boolean checkedMapButton;
    boolean checkedWebButton;

    //*********************onCreate()****************************
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_select_phone_web_map);

        //get user input and convert to string
        userInput = (EditText)findViewById(R.id.userInputId);
        //userInputString = String.valueOf(userInput);

        radioGroup = (RadioGroup)findViewById(R.id.radioGroupId);
        radioGroup.setOnCheckedChangeListener(this);

        goButton = (Button)findViewById(R.id.goButtonId);
        goButton.setOnClickListener(this);
    }//end onCreate

    //*********************onCreate()****************************
    //triggered by user choosing a radiobutton
    //int id is generated by R.java
    @Override
    public void onCheckedChanged(RadioGroup radioGroup, int id)
    {
        //store the id of which button was picked
        switch (id)
        {
        case R.id.radioPhoneId:
            toastMessage = "Enter a phone number";
            showToast(toastMessage);
            userInput.setInputType(InputType.TYPE_CLASS_PHONE);
            enablePhone();
            break;
        case R.id.radioWebId:
            toastMessage = "Enter a web address";
            showToast(toastMessage);
            userInput.setInputType(InputType.
                TYPE_TEXT_VARIATION_WEB_EDIT_TEXT);
            enableWeb();
            break;
        case R.id.radioGmapId:
            toastMessage = "Enter your coordinates separated " +
                "a comma \n (ie. latitude, longitude)";
            showToast(toastMessage);
            userInput.setInputType(InputType.TYPE_CLASS_TEXT);
            enableMap();
            break;
        }
    }

    //*********************onClick()*****************************
    @Override
    public void onClick(View v)
    {
        //convert user input to string
        userInputString = userInput.getText().toString();

        if(checkedPhoneButton)
        {
            Intent inPhone = new Intent(Intent.ACTION_CALL);
            inPhone.setData(Uri.parse("tel:" + userInputString));
            startActivity(inPhone);
        }
        else if (checkedWebButton)
        {
            Intent inWeb = new Intent(Intent.ACTION_VIEW);
            inWeb.setData(Uri.parse("http://" +
            userInputString));
            startActivity(inWeb);
        }
        else if (checkedMapButton)
        {
            Intent inMap = new Intent(Intent.ACTION_VIEW);
            inMap.setData(Uri.parse("geo:" + userInputString));
            startActivity(inMap);
        }
    }

    //*********************showToast()***************************
    public void showToast(String toastMessage)
    {
        Toast t = Toast.makeText(getBaseContext(),
            toastMessage,Toast.LENGTH_SHORT);
        t.setGravity(Gravity.CENTER,0,60);
        t.show();
    }

    //*********************enablePhone()*************************
    public void enablePhone()
    {
        checkedPhoneButton = true;
        checkedMapButton = false;
        checkedWebButton = false;
    }

    //*********************enableMap()***************************
    public void enableMap()
    {
        checkedPhoneButton = false;
        checkedMapButton = true;
        checkedWebButton = false;
    }

    //*********************enableWeb()***************************
    public void enableWeb()
    {
        checkedPhoneButton = false;
        checkedMapButton = false;
        checkedWebButton = true;
    }
}//end class
