//   Author:   Tadhg Coffey
//   Date  :   3/26/14
//   Homework assignment : 6
//   File: R.java from Draw Bubbles
//   Objective : To draw bubbles (circles) of different, size,
//      color and position when the user clicks a button. A clear
//      button deletes all.
//***************************************************************

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.drawbubbles.drawbubbles;

public final class R 
{
    public static final class attr 
	{
    }
    public static final class dimen 
	{
        public static final int activity_horizontal_margin
			=0x7f040000;
        public static final int activity_vertical_margin
			=0x7f040001;
    }
    public static final class drawable 
	{
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id 
	{
        public static final int action_settings=0x7f080003;
        public static final int clearButtonId=0x7f080001;
        public static final int drawButtonId=0x7f080000;
        public static final int drawingAreaId=0x7f080002;
    }
    public static final class layout 
	{
        public static final int activity_draw=0x7f030000;
        public static final int activity_draw_view=0x7f030001;
    }
    public static final class menu 
	{
        public static final int draw=0x7f070000;
        public static final int draw_view=0x7f070001;
    }
    public static final class string 
	{
        public static final int action_settings=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int hello_world=0x7f050002;
        public static final int title_activity_draw_view
			=0x7f050003;
    }
    public static final class style 
	{
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f060000;
    }
}
